/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto07.poo2;

/**
 *
 * @author jyoshiriro
 */
public class TelaCofrinho extends javax.swing.JFrame {
    
    /*
    "cofrinho1" é um "atributo de instância" da "TelaCofrinho"
    "cofrinho1" é um OBJETO do tipo "Cofrinho"
    */
    Cofrinho cofrinho1 = new Cofrinho();
    
    // o mesmo vale para "cofrinho2" e "cofrinho3"
    Cofrinho cofrinho2 = new Cofrinho();
    Cofrinho cofrinho3 = new Cofrinho();
    
    
    void atualizarSaldos() {
        lbSaldo1.setText(cofrinho1.saldo.toString());
        lbSaldo2.setText(cofrinho2.saldo.toString());
        lbSaldo3.setText(cofrinho3.saldo.toString());
    }
    
    
    /** 
     * método que recebe um objeto do tipo "Cofrinho"
     * e tenta reduzir seu saldo em 1,00
     * porém, um cofrinho não pode ter saldo negativo após o saque
     * use esse método nos eventos dos 3 botões de "tirar 1,00"
    **/
    void tirar1real(Cofrinho algumCofrinho) {
        // se, ao tirar 1 do saldo de "algumCofrinho"
        // o saldo for >=0, então pode tirar 1
        if (algumCofrinho.saldo - 1 >= 0) {
            algumCofrinho.saldo -= 1;
            atualizarSaldos();
        }
    }
    
    /** método que recebe um objeto do tipo "Cofrinho"
     * e tenta aumentar seu saldo em 2,00
     * porém, um cofrinho não pode ter mais de 20,00
     * use esse método nos eventos dos 3 botões de "depositar 2,00"
    **/
    void depositar2reais(Cofrinho algumCofrinho) {
        if (algumCofrinho.saldo + 2 <= 20) {
            algumCofrinho.saldo += 2;
            atualizarSaldos();
        }
    }

    /**
     * Creates new form TelaConfrinho
     */
    public TelaCofrinho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbSaldo1 = new javax.swing.JLabel();
        btDepositar1 = new javax.swing.JButton();
        btTirar1 = new javax.swing.JButton();
        btDepositar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbSaldo2 = new javax.swing.JLabel();
        btTirar2 = new javax.swing.JButton();
        btTirar3 = new javax.swing.JButton();
        btDepositar3 = new javax.swing.JButton();
        lbSaldo3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valor guardado:");

        lbSaldo1.setText("0");

        btDepositar1.setText("Depositar 2,00");
        btDepositar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositar1ActionPerformed(evt);
            }
        });

        btTirar1.setText("Tirar 1,00");
        btTirar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTirar1ActionPerformed(evt);
            }
        });

        btDepositar2.setText("Depositar 2,00");
        btDepositar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositar2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor guardado:");

        lbSaldo2.setText("0");

        btTirar2.setText("Tirar 1,00");
        btTirar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTirar2ActionPerformed(evt);
            }
        });

        btTirar3.setText("Tirar 1,00");
        btTirar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTirar3ActionPerformed(evt);
            }
        });

        btDepositar3.setText("Depositar 2,00");
        btDepositar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositar3ActionPerformed(evt);
            }
        });

        lbSaldo3.setText("0");

        jLabel3.setText("Valor guardado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSaldo1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDepositar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btTirar1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSaldo2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDepositar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btTirar2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSaldo3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDepositar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btTirar3)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbSaldo1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDepositar1)
                    .addComponent(btTirar1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbSaldo2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDepositar2)
                    .addComponent(btTirar2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbSaldo3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDepositar3)
                    .addComponent(btTirar3))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDepositar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositar1ActionPerformed
        depositar2reais(cofrinho1);
    }//GEN-LAST:event_btDepositar1ActionPerformed

    private void btTirar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTirar1ActionPerformed
        tirar1real(cofrinho1);
    }//GEN-LAST:event_btTirar1ActionPerformed

    private void btDepositar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositar2ActionPerformed
        depositar2reais(cofrinho2);
    }//GEN-LAST:event_btDepositar2ActionPerformed

    private void btTirar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTirar2ActionPerformed
        tirar1real(cofrinho2);
    }//GEN-LAST:event_btTirar2ActionPerformed

    private void btTirar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTirar3ActionPerformed
        tirar1real(cofrinho3);
    }//GEN-LAST:event_btTirar3ActionPerformed

    private void btDepositar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositar3ActionPerformed
        depositar2reais(cofrinho3);
    }//GEN-LAST:event_btDepositar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCofrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCofrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCofrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCofrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCofrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDepositar1;
    private javax.swing.JButton btDepositar2;
    private javax.swing.JButton btDepositar3;
    private javax.swing.JButton btTirar1;
    private javax.swing.JButton btTirar2;
    private javax.swing.JButton btTirar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbSaldo1;
    private javax.swing.JLabel lbSaldo2;
    private javax.swing.JLabel lbSaldo3;
    // End of variables declaration//GEN-END:variables
}
